languageCode = "en-us"
title = "My New Hugo Site"
baseurl = "http://example.org/"
#theme = 'startbootstrap-clean-blog'
theme = 'mainroad'

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "about"
  url = "/about/"
  weight = -180
